# ----------------------------
# Makefile Options
# ----------------------------

NAME = flagon
DESCRIPTION = "Ag C Agon flappy bird"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -Wimplicit-function-declaration
CXXFLAGS = -Wall -Wextra -Oz -Wimplicit-function-declaration

# ----------------------------

include $(shell cedev-config --makefile)
